
title: Miciah Martin Full Stack Developer
email: martindynamics@yahoo.com
description: Miciah Martin is a Full Stack Developer working from Reno, NV. Miciah works both freelance and permanent employee positions.
baseurl: 
url: https://www.miciahmartin.com/
twitter_username: MiciahMartin
github_username: Miciah1
author: miciah@ctemplar.com


sass:
    load_paths: _sass
    sass_dir: _sass


