
title: Miciah Martin Full Stack Developer
email: 'martindynamics@yahoo.com'
rss: true 
description: Miciah Martin is a Full Stack Developer working from Reno, NV. Miciah works both freelance and permanent employee positions.
baseurl: https://martindynamix.github.io/github.io/
url: https://martindynamix.github.io/github.io
twitter_username: MiciahMartin
github_username: Miciah1
author: miciah@ctemplar.com


sass:
    load_paths: _sass
    sass_dir: _sass


# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

# Fill in your Google Analytics ID to track your website using Google Analytics
google_analytics: "sJA7DAfBek3WtJ1Cpkx-Wj3tsdyX2VzgOde4DDgfs9w"
        
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

