
title: Miciah Martin Full Stack Developer
email: 'martindynamics@yahoo.com'
rss: true 
description: Miciah Martin is a Full Stack Developer working from Reno, NV. Miciah works both freelance and permanent employee positions.
baseurl: ...
url: https://martindynamix.github.io/github.io
twitter_username: MiciahMartin
github_username: Miciah1
author: miciah@ctemplar.com


sass:
    load_paths: _sass
    sass_dir: _sass


